In [103]:
%cd /home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local
%pwd

/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local

'/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local'

In [104]:
import os
import glob
import csv
import pandas as pd 
import shutil 

def load_df_from_csv(csv_file_path:str, sep = ',') -> pd.DataFrame :

    df = pd.read_csv(csv_file_path,sep)

    return df 

def get_duplicates_from_df (df,key,Output_path,NAME_OF_DF) : 
    
    df = df[df.duplicated(f'{key}',keep=False)]
    try: 
        df = df.drop(columns=['Unnamed: 0'])
    except:
        pass
    
    df = df.sort_values(f'{key}')
    df.to_csv(f'{Output_path}/duplicates_in_'+f'{NAME_OF_DF}' +'.csv')




DAIRY_OLD_PATH = '/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Data/Dor-alon-files/sku-old.csv'
DAIRY_NEW_PATH = '/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Data/Dor-alon-files/sku-new.csv'


dairy_old_df = load_df_from_csv(DAIRY_OLD_PATH,sep ='\t')
dairy_new_df = load_df_from_csv(DAIRY_NEW_PATH,sep ='\t')

# product_list_df['UPC'] = product_list_df['UPC'].astype(str)
# product_list_df = product_list_df.drop(columns=['Unnamed: 0'])
# product_list_df['Product_List'] = 'Yes' 
# product_list_df.to_csv('Outputs/product_list_df.csv')

# images_dir_df['UPC'] = images_dir_df['UPC'].astype(str)
# # images_dir_df['Number_of_images'] = images_dir_df['Number_of_images'].astype(str)
# images_dir_df = images_dir_df.drop(columns=['Unnamed: 0'])
# images_dir_df['Image_Dirs'] = 'Yes' 
# # images_dir_df = images_dir_df[['UPC','Image_Dirs','Number_of_images']]
# # images_dir_df = images_dir_df[['UPC']]
# images_dir_df.to_csv('Outputs/images_dir_df.csv')


# thumbnails_df['UPC'] = thumbnails_df['UPC'].astype(str)
# thumbnails_df = thumbnails_df.drop(columns=['Unnamed: 0'])
# thumbnails_df['Thumbnails'] = 'Yes'
# thumbnails_df.to_csv('Outputs/thumbnails_df.csv')


# product_list_df.shape , images_dir_df.shape ,thumbnails_df.shape #((677, 4), (285, 3)) ,(611, 2)
# product_list_df.dtypes , images_dir_df.dtypes, thumbnails_df.dtypes  # all object dtype


# ((293, 6), (682, 6), (677, 6), (298, 6))

# res_df = pd.merge(merged_outer,thumbnails_df,how = 'outer' , on = 'UPC') # (293,6)
# res_df[['Product_List','Image_Dirs','Thumbnails']] = res_df[['Product_List','Image_Dirs','Thumbnails']].fillna(value = 'No')
# res_df[['CATEGORY','SUB_CATEGORY']] = res_df[['CATEGORY','SUB_CATEGORY']].fillna(value = '--')

# res_df = res_df[['UPC',	'CATEGORY',	'SUB_CATEGORY',	'Product_List',	'Image_Dirs','Thumbnails']]
# res_df.to_csv('Outputs/res_df.csv')

<ipython-input-104-18aaab1ef184>:31: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  dairy_old_df = load_df_from_csv(DAIRY_OLD_PATH,sep ='\t')
<ipython-input-104-18aaab1ef184>:32: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  dairy_new_df = load_df_from_csv(DAIRY_NEW_PATH,sep ='\t')

In [105]:
merged_outer = pd.merge(dairy_new_df,dairy_old_df,how = 'outer' , on = 'SKU')
merged_inner = pd.merge(dairy_new_df,dairy_old_df,how = 'inner' , on = 'SKU') # (293,6)
merged_left =  pd.merge(dairy_new_df,dairy_old_df,how = 'left' , on = 'SKU') # (677,6)
merged_right = pd.merge(dairy_new_df,dairy_old_df,how = 'right' , on = 'SKU') # (298,6)


merged_left_list = merged_left['SKU'].to_list()    
merged_right_list = merged_right['SKU'].to_list()
merged_inner_list = merged_inner['SKU'].to_list()

# new_annotations_strings = [item for item in merged_left if item not in merged_inner]
new_annotations_strings = set.difference(set(merged_left_list),set(merged_inner_list))
old_annotations_strings = set.difference(set(merged_right_list),set(merged_inner_list))

In [106]:
new_annotations_strings

# old_annotations_strings

{'4120634',
 '7290000040974',
 '7290000041858_Yotvata enriched with sour cream 200 ml 15%_EnrichedCream',
 '7290000044248_Tnuva white buttermilk pasteurized milk 1.5%_Rivion',
 '7290000045917_Roll goat cheese 200g Fromaz_Fromaz',
 '7290000048185_5% cream cheese 250g Mehadrin_WhiteCreamTnuva',
 '7290000048437_Piraeus salty fat 5%_Piraeus',
 '7290000050447',
 '7290000052250',
 '7290000055329_Yoplait yogurt drink strawberry hotel_YoplaitDrink',
 '7290002824640_Ski white cheese 250g 5%_ski',
 '7290003029372',
 '7290004120634_Piraeus Bulgarian 5% fat_Piraeus',
 '7290004125417_White Age yield 206 grams of 3%_Gil',
 '7290004125578_Fortified soy drink 1 liter_Alternative',
 '7290004127077_Cottage 3% cup 250g_Cottage-Tnuva',
 '7290004130794_Natural Soy drink less sweetened 1 liter_Alternative',
 '7290004584351_Natural symphony 5%_symphony',
 '7290014761056_YOLO milk chocolate 123 g_YOLO',
 '7290014761063_YOLO dark chocolate 123 g_YOLO',
 '7290014761070_YOLO white chocolate delicacy 123g_YOLO',
 '7290014761612',
 '7290014763272_BIO soy drink strawberry banana_AlternativeDrink250',
 '7290014763289_BIO soy drink apple raspberry_AlternativeDrink250',
 '7290102398614_Milk beverage banana flavoured Yotvata 1 liter_Yotvata-BigBottle',
 '7290107932080_3% milk enriched bottle 1 liter_MilkYotvata',
 '7290107932134_1% milk enriched bottle 1 liter_MilkLowFatYotvata',
 '7290107954976_Peru Yotvata drink coffee 350_ProDrink',
 '7290110325619_Oat drink_Alternative',
 '7290110325886_GO iced coffee yield 250 ml_GoDrink250',
 '7290110325893_GO iced coffee yield 340 ml_Go-Drink',
 '7290110326999_YOLO drink chocolate milk 340 ml Classic_YOLO',
 '7290110563462',
 '7290112355522',
 'Abadi_856591000062',
 'Al Nakhla with hel 250g_7290002771111',
 'AlternativeDrink250_7290014763272',
 'AlternativeDrink250_7290014763289',
 'Alternative_7290110325619',
 'Bisli_7290000066226_200gr',
 'Blu_5904941751302',
 'Butter_72963104',
 'ChocoTnuvaBottle_4131531_1L',
 'Cottage Strauss_7290011194246',
 'Cottage Tnuva_4127329',
 'Cottage Tnuva_4127336',
 'Danone_408316',
 'Danone_4584528',
 'Danone_7290110565527',
 'Danone_7290110566975',
 'Danone_7290110568276',
 'Doritos_7290010117864',
 'Doritos_7290100850916_70gr',
 'Doritos_7290100850923_70gr',
 'Doritos_7290106528567_185gr',
 'Doritos_7290106667266_185gr',
 'Elite coffee Names 200g_7290000176420',
 'Elite coffee Turkey 100g_7290000176062',
 'Fromaz_45917',
 'Go Drink_7290110323066',
 'GoDrink250_7290014763678',
 'Gush Halav_4122195',
 'Gush-Halav_Gush milk cheese sliced \u200b\u200b200g_7290004122195',
 'Jacobs kronung 47.5g_8714599513828',
 'Mana Hama_67599',
 'Mana Hama_7290100680650',
 'Names Bacos_7290100247808',
 'Names Bacos_7290112497291',
 'Piraeus_51710',
 'Prichiot Fitness_7290112967381',
 'ProDrink_7290112330970',
 'Rivion_43890_1L',
 'Rivion_44248',
 'Shokolit Elite 500g_7290000174723',
 'Snyders_77975094006',
 'Tapuchips_7290000178707_50gr',
 'Tapuchips_7290000178721__200gr',
 'Tapuchips_7290005200786_50gr',
 'Tapuchips_7290008752244',
 'Tapuchips_7290008753111_50gr',
 'Tapuchips_7290102030330_200gr',
 'Tapuchips_7290104722530_200gr',
 'Tapuchips_7290106662025',
 'Tapuchips_7290107942355',
 'Tapuchips_7290110561918',
 'Tapuchips_7290112359018',
 'Tapuchips_7290115676990',
 "Taster's Choice 200g_7290000072753",
 'Tnuva-SmallBottle_4136154_340ML',
 'Tnuva-SmallBottle_52304_340ML',
 'YOLO_7290014761056',
 'YOLO_7290014761063',
 'YOLO_7290110326999',
 'Yoplait_7290110324612',
 'Yoplait_7290110326234',
 'Yotvata-BigBottle_3029532_1L',
 'Yotvata-BigBottle_3029907_1L',
 'symphony_4584351'}

In [107]:
set.intersection(new_annotations_strings,old_annotations_strings)

set()

In [108]:
merged_outer.to_csv('/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Outputs/outer-dairy-old-new-merged.csv')
merged_left.to_csv('/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Outputs/left-dairy-old-new-merged.csv')
merged_right.to_csv('/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Outputs/right-dairy-old-new-merged.csv')
merged_inner.to_csv('/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task/Outputs/inner-dairy-old-new-merged.csv')

In [109]:

merged_left = merged_left['SKU'].to_list()
merged_inner = merged_inner['SKU'].to_list()

# new_annotations_strings = [item for item in merged_left if item not in merged_inner]
new_annotations_strings = set.difference(set(merged_left),set(merged_inner))
old_annotations_strings = set.difference(set(merged_right),set(merged_inner))

In [110]:
new_annotations_strings

{'4120634',
 '7290000040974',
 '7290000041858_Yotvata enriched with sour cream 200 ml 15%_EnrichedCream',
 '7290000044248_Tnuva white buttermilk pasteurized milk 1.5%_Rivion',
 '7290000045917_Roll goat cheese 200g Fromaz_Fromaz',
 '7290000048185_5% cream cheese 250g Mehadrin_WhiteCreamTnuva',
 '7290000048437_Piraeus salty fat 5%_Piraeus',
 '7290000050447',
 '7290000052250',
 '7290000055329_Yoplait yogurt drink strawberry hotel_YoplaitDrink',
 '7290002824640_Ski white cheese 250g 5%_ski',
 '7290003029372',
 '7290004120634_Piraeus Bulgarian 5% fat_Piraeus',
 '7290004125417_White Age yield 206 grams of 3%_Gil',
 '7290004125578_Fortified soy drink 1 liter_Alternative',
 '7290004127077_Cottage 3% cup 250g_Cottage-Tnuva',
 '7290004130794_Natural Soy drink less sweetened 1 liter_Alternative',
 '7290004584351_Natural symphony 5%_symphony',
 '7290014761056_YOLO milk chocolate 123 g_YOLO',
 '7290014761063_YOLO dark chocolate 123 g_YOLO',
 '7290014761070_YOLO white chocolate delicacy 123g_YOLO',
 '7290014761612',
 '7290014763272_BIO soy drink strawberry banana_AlternativeDrink250',
 '7290014763289_BIO soy drink apple raspberry_AlternativeDrink250',
 '7290102398614_Milk beverage banana flavoured Yotvata 1 liter_Yotvata-BigBottle',
 '7290107932080_3% milk enriched bottle 1 liter_MilkYotvata',
 '7290107932134_1% milk enriched bottle 1 liter_MilkLowFatYotvata',
 '7290107954976_Peru Yotvata drink coffee 350_ProDrink',
 '7290110325619_Oat drink_Alternative',
 '7290110325886_GO iced coffee yield 250 ml_GoDrink250',
 '7290110325893_GO iced coffee yield 340 ml_Go-Drink',
 '7290110326999_YOLO drink chocolate milk 340 ml Classic_YOLO',
 '7290110563462',
 '7290112355522',
 'Abadi_856591000062',
 'Al Nakhla with hel 250g_7290002771111',
 'AlternativeDrink250_7290014763272',
 'AlternativeDrink250_7290014763289',
 'Alternative_7290110325619',
 'Bisli_7290000066226_200gr',
 'Blu_5904941751302',
 'Butter_72963104',
 'ChocoTnuvaBottle_4131531_1L',
 'Cottage Strauss_7290011194246',
 'Cottage Tnuva_4127329',
 'Cottage Tnuva_4127336',
 'Danone_408316',
 'Danone_4584528',
 'Danone_7290110565527',
 'Danone_7290110566975',
 'Danone_7290110568276',
 'Doritos_7290010117864',
 'Doritos_7290100850916_70gr',
 'Doritos_7290100850923_70gr',
 'Doritos_7290106528567_185gr',
 'Doritos_7290106667266_185gr',
 'Elite coffee Names 200g_7290000176420',
 'Elite coffee Turkey 100g_7290000176062',
 'Fromaz_45917',
 'Go Drink_7290110323066',
 'GoDrink250_7290014763678',
 'Gush Halav_4122195',
 'Gush-Halav_Gush milk cheese sliced \u200b\u200b200g_7290004122195',
 'Jacobs kronung 47.5g_8714599513828',
 'Mana Hama_67599',
 'Mana Hama_7290100680650',
 'Names Bacos_7290100247808',
 'Names Bacos_7290112497291',
 'Piraeus_51710',
 'Prichiot Fitness_7290112967381',
 'ProDrink_7290112330970',
 'Rivion_43890_1L',
 'Rivion_44248',
 'Shokolit Elite 500g_7290000174723',
 'Snyders_77975094006',
 'Tapuchips_7290000178707_50gr',
 'Tapuchips_7290000178721__200gr',
 'Tapuchips_7290005200786_50gr',
 'Tapuchips_7290008752244',
 'Tapuchips_7290008753111_50gr',
 'Tapuchips_7290102030330_200gr',
 'Tapuchips_7290104722530_200gr',
 'Tapuchips_7290106662025',
 'Tapuchips_7290107942355',
 'Tapuchips_7290110561918',
 'Tapuchips_7290112359018',
 'Tapuchips_7290115676990',
 "Taster's Choice 200g_7290000072753",
 'Tnuva-SmallBottle_4136154_340ML',
 'Tnuva-SmallBottle_52304_340ML',
 'YOLO_7290014761056',
 'YOLO_7290014761063',
 'YOLO_7290110326999',
 'Yoplait_7290110324612',
 'Yoplait_7290110326234',
 'Yotvata-BigBottle_3029532_1L',
 'Yotvata-BigBottle_3029907_1L',
 'symphony_4584351'}

In [111]:
a = 'Corona-yellow-beers_19-02-37_18-08-2021'
a.split(sep='_')[-1]

'18-08-2021'

In [112]:
%cd /home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task

/home/arpalus/Work_Eldad/Arpalus_Code/Eldad-Local/Eldad-Automatic-Deployment/J_Task

In [113]:
import pandas as pd 
import os,glob

def load_df_from_csv(csv_file_path:str) -> pd.DataFrame :

    df = pd.read_csv(csv_file_path,sep='\t')
    
    return df 

def load_df_from_xl(file_name,sheet_name = None):
    
    xl_file = pd.ExcelFile(file_name)

    dfs = {sheet_name: xl_file.parse(sheet_name) 
          for sheet_name in xl_file.sheet_names}

    if sheet_name:
          
          return dfs[f'{sheet_name}']

    return dfs 

# def main():

DF_ALL_TIME_PL_PATH = 'Data/merge-task-Hadar/big_all-time_df_PL.xlsx'
IN_HOUSE_PL_PATH = 'Data/merge-task-Hadar/in-house-PL.tsv'
df_all_time_PL = load_df_from_xl(DF_ALL_TIME_PL_PATH,sheet_name='Sheet1')
in_house_PL = load_df_from_csv(IN_HOUSE_PL_PATH)

# if __name__ == "__main__":

#     main()

#pre-processing 
df_all_time_PL = df_all_time_PL[['SKU-KEY','Y','X','Z']]
df_all_time_PL.columns = ['SKU','Width','Height','Depth']
convert_dict = {'SKU': int,
                'Width': float,
                'Height': float,
                'Depth': float
               }
df_all_time_PL = df_all_time_PL.astype(convert_dict)
df_all_time_PL.loc[:,'Width'] = df_all_time_PL.loc[:,'Width'] / 100
df_all_time_PL.loc[:,'Height'] = df_all_time_PL.loc[:,'Height'] / 100
df_all_time_PL.loc[:,'Depth'] = df_all_time_PL.loc[:,'Depth'] / 100

in_house_PL = in_house_PL[['SKU','Width','Height','Depth']]

# df_all_time_PL['SKU']
# print(df_all_time_PL[df_all_time_PL['SKU']==856591000109].index.values)
# print(df_all_time_PL[df_all_time_PL['SKU']==856591000109])

#sql-merge-like

df_all_time_PL.head(),in_house_PL.head()

In [115]:
df_1 = in_house_PL.merge(df_all_time_PL,on ='SKU', how = 'inner') #511
df_2 = in_house_PL.merge(df_all_time_PL,on ='SKU', how = 'left') #763

df_3 = pd.concat([df_1, df_2])
# df_3 = df_3.drop_duplicates(subset = ['SKU'], keep=False)
df_3

               SKU  Width_x  Height_x  Depth_x  Width_y  Height_y  Depth_y
0     856591000062    0.150     0.270    0.050    0.150     0.080    0.250
1     856591000109    0.150     0.270    0.050    0.150     0.080    0.250
2    7290014760141    0.075     0.232    0.070    0.070     0.240    0.070
3    7290110325619    0.080     0.230    0.080    0.900     2.350    0.600
4    7290014763289    0.060     0.160    0.075    0.055     0.160    0.055
..             ...      ...       ...      ...      ...       ...      ...
758  7290110328382    0.095     0.072    0.095    0.950     0.720    0.950
759  7290110321796    0.095     0.120    0.095    0.770     0.970    0.770
760  7290014761070    0.067     0.063    0.063    0.067     0.063    0.063
761  7290014761414    0.088     0.047    0.047    0.088     0.047    0.047
762  7290008693134    0.075     0.061    0.125      NaN       NaN      NaN

[1274 rows x 7 columns]

In [102]:
df_1 , df_2

(               SKU  Width_x  Height_x  Depth_x  Width_y  Height_y  Depth_y
 0     856591000062    0.150     0.270    0.050    0.150     0.080    0.250
 1     856591000109    0.150     0.270    0.050    0.150     0.080    0.250
 2    7290014760141    0.075     0.232    0.070    0.070     0.240    0.070
 3    7290110325619    0.080     0.230    0.080    0.900     2.350    0.600
 4    7290014763289    0.060     0.160    0.075    0.055     0.160    0.055
 ..             ...      ...       ...      ...      ...       ...      ...
 506  7290110321284    0.075     0.050    0.075    0.075     0.050    0.075
 507  7290110328382    0.095     0.072    0.095    0.950     0.720    0.950
 508  7290110321796    0.095     0.120    0.095    0.770     0.970    0.770
 509  7290014761070    0.067     0.063    0.063    0.067     0.063    0.063
 510  7290014761414    0.088     0.047    0.047    0.088     0.047    0.047

 [511 rows x 7 columns],
                SKU  Width_x  Height_x  Depth_x  Width_y  Height_y  Depth_y
 0     856591000062    0.150     0.270    0.050    0.150     0.080    0.250
 1    7290002132011    0.170     0.270    0.050      NaN       NaN      NaN
 2     856591000109    0.150     0.270    0.050    0.150     0.080    0.250
 3    7290002771111    0.110     0.150    0.057      NaN       NaN      NaN
 4    7290014760141    0.075     0.232    0.070    0.070     0.240    0.070
 ..             ...      ...       ...      ...      ...       ...      ...
 758  7290110328382    0.095     0.072    0.095    0.950     0.720    0.950
 759  7290110321796    0.095     0.120    0.095    0.770     0.970    0.770
 760  7290014761070    0.067     0.063    0.063    0.067     0.063    0.063
 761  7290014761414    0.088     0.047    0.047    0.088     0.047    0.047
 762  7290008693134    0.075     0.061    0.125      NaN       NaN      NaN

 [763 rows x 7 columns])

In [97]:
df_1 = df_1[['SKU','Width_x','Height_x','Depth_x']]
df_3 = df_3[['SKU','Width_x','Height_x','Depth_x']]
res_df = pd.concat([df_1, df_3])
res_df.sort_values(by = 'SKU').reset_index()

     index            SKU  Width_x  Height_x  Depth_x
0      361              2    1.200     0.180    0.400
1      304          63133    0.065     0.160    0.020
2      228          65557    0.080     0.100    0.020
3      229          67599    0.080     0.100    0.020
4      227          73750    0.080     0.100    0.020
..     ...            ...      ...       ...      ...
758    388  8850389115336    0.080     0.295    0.080
759    461  8907931003600    0.130     0.190    0.050
760    326  9044400841000    0.080     0.220    0.050
761    465  9310072028743    0.240     0.075    0.035
762    464  9310072028750    0.240     0.075    0.035

[763 rows x 5 columns]